src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Electronic_version_of_FLAC_News__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Wishes to receive a copy of FLAC news by email</description>
        <label>Electronic version of FLAC News</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Home_Area_Town__c</fullName>
        <description>Temp used when Contact is created from a lead to populate the home address field</description>
        <label>Lead Home Area Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Home_City_County__c</fullName>
        <description>Temp used when Contact is created from a lead to populate the home address field</description>
        <label>Lead Home City County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Home_Phone__c</fullName>
        <description>Temp used when Contact is created from a lead to populate the home phone field</description>
        <label>Lead Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Lead_Home_Street__c</fullName>
        <description>Temp used when Contact is created from a lead to populate the home address field</description>
        <label>Lead Home Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Main_FLAC_Mailing_List__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Tick this box to add contact to the main FLAC mailing list e.g. for Dave Ellis annual lecture invitation</inlineHelpText>
        <label>Main FLAC Mailing List</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Receives_FLAC_News__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Receives FLAC News</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>npe01__Primary_Address_Type__c</fullName>
        <description>Which type of address is the mailing address?</description>
        <label>Primary Address Type</label>
        <picklist>
            <picklistValues>
                <fullName>Work</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>npe01__Secondary_Address_Type__c</fullName>
        <description>What type of address is the other address?</description>
        <label>Secondary Address Type</label>
        <picklist>
            <picklistValues>
                <fullName>Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>FLAC_Volunteer</fullName>
        <active>true</active>
        <description>Use for FLAC volunteers</description>
        <label>FLAC Volunteer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <recordTypes>
        <fullName>Volunteer</fullName>
        <active>true</active>
        <businessProcess>Volunteer</businessProcess>
        <description>Signup to volunteer from web site</description>
        <label>Volunteer</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/MapExtraLeadFieldsToContact.cls
/*
Author: Eamon Kelly, Enclude
Purpose: Copy temp volunteer fields from lead convert into contact that are not accessible to the map lead fields page  
Called from: Trigger dispatcher
Tested in: 
*/
public with sharing class MapExtraLeadFieldsToContact implements TriggerDispatcher.ITriggerEntry
{
	public void MainEntry (String TriggerObject, Boolean isBefore, Boolean isDelete, Boolean isAfter, Boolean isInsert, Boolean isUpdate, Boolean isExecuting,
		List<SObject> newList, Map<Id, SObject> newMap, List<SObject> oldList, Map<Id, SObject> oldMap)
	{
		if (isInsert)
		{
			ContactBeingInserted (newList);
		}
	}

	public void ContactBeingInserted (List<Contact> newVolunteers)
	{
		// Contact record type needs to change to volunteer
		ID volunteerRecordTypeID = [select ID from RecordType where sObjectType='Contact' and DeveloperName='FLAC_Volunteer' limit 1].id;
		for (Contact oneVolunteer : newVolunteers)
		{
			oneVolunteer.RecordTypeID = volunteerRecordTypeID;
			if (oneVolunteer.LeadSource == 'Volunteer')
			{
				oneVolunteer.HomePhone = oneVolunteer.Lead_Home_Phone__c;
				oneVolunteer.Main_FLAC_Mailing_List__c = true;
				oneVolunteer.Receives_FLAC_News__c = true;
				
				// by default, the work address comes in as the Mailing Address, but this is the primary address in the NPSP
				if (oneVolunteer.npe01__Primary_Address_Type__c.Contains ('Home'))
				{
					oneVolunteer.npe01__Primary_Address_Type__c = 'Home';
					oneVolunteer.npe01__Secondary_Address_Type__c = 'Work';
					oneVolunteer.OtherStreet = oneVolunteer.MailingStreet;
					oneVolunteer.OtherCity = oneVolunteer.MailingCity;
					oneVolunteer.OtherState = oneVolunteer.MailingState;
					oneVolunteer.MailingStreet = oneVolunteer.Lead_Home_Street__c;
					oneVolunteer.MailingCity = oneVolunteer.Lead_Home_Area_Town__c;
					oneVolunteer.MailingState = oneVolunteer.Lead_Home_City_County__c;
				}
				else
				{
					oneVolunteer.npe01__Secondary_Address_Type__c = 'Home';
					oneVolunteer.OtherStreet = oneVolunteer.Lead_Home_Street__c;
					oneVolunteer.OtherCity = oneVolunteer.Lead_Home_Area_Town__c;
					oneVolunteer.OtherState = oneVolunteer.Lead_Home_City_County__c;
					if (oneVolunteer.npe01__Primary_Address_Type__c.Contains ('email'))
					{
						oneVolunteer.Electronic_version_of_FLAC_News__c = true;
					}
					oneVolunteer.npe01__Primary_Address_Type__c = 'Work';
				}
			}
		}
	}

}